# Generated by Django 5.1.1 on 2024-10-11 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recursos_delete_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recursos',
            options={'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
        migrations.RemoveField(
            model_name='recursos',
            name='icones',
        ),
        migrations.AddField(
            model_name='recursos',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-Infinite', 'Dispositivos'), ('lni-engrenagens', 'Engrenagens'), ('lni-design', 'Design'), ('lni-responsive', 'Responsividade'), ('lni-information', 'FormContact')], default=django.utils.timezone.now, max_length=100, verbose_name='Icone'),
            preserve_default=False,
        ),
    ]
