# Generated by Django 5.1.1 on 2024-10-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_recursos_options_remove_recursos_icones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-Infinite', 'Dispositivos'), ('lni-cog', 'Engrenagens'), ('lni-layers', 'Design'), ('lni-responsive', 'Responsividade'), ('lni-information', 'FormContact')], max_length=100, verbose_name='Icone'),
        ),
    ]
