# Generated by Django 5.1.1 on 2024-10-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_recursos_icone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recursos',
            old_name='icone',
            new_name='icones',
        ),
    ]
