# Generated by Django 5.1.1 on 2024-10-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_icone_recursos_icones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='icones',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-starts-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], max_length=100, verbose_name='Icone'),
        ),
    ]
