# Generated by Django 5.1.1 on 2024-10-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_recursos_icones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='descricao',
            field=models.CharField(max_length=5000, verbose_name='Descricao'),
        ),
    ]
